{% set name = "sphobjinv" %}
{% set version = "2.3.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1c874a368460851352d45c92afa172b5c42653b47e2e70d78d61dac93308aa9d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - sphobjinv = sphobjinv.cli.core:main

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - attrs >=19.2
    - certifi
    - jsonschema >=3.0

test:
  requires:
    - pip
    - pytest
    - pytest_check >=1.1.2
    - pytest-ordering
    - pytest-timeout
    - sphinx == 7.1.2
    - dictdiffer
    - stdio-mgr >= 1.0.1
  imports:
    - sphobjinv
  source_files:
    - README.md
    - tox.ini
    - requirements-dev.txt
    - conftest.py
    - tests/
  commands:
    - pip check
    - pytest -k "not readme"

about:
  home: https://github.com/bskinn/sphobjinv
  summary: 'Toolkit for manipulation and inspection of Sphinx objects.inv files'
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
    - src/sphobjinv/_vendored/fuzzywuzzy/LICENSE.txt
  doc_url: https://sphobjinv.readthedocs.io/en/latest/
  dev_url: https://github.com/bskinn/sphobjinv

extra:
  recipe-maintainers:
    - bskinn
    - anjos
